### ISSUE TITLE
[*] Error message ==> JSON Query to accounts/login/: Could not find "window._sharedData" in html response.

### ISSUE THREAD

**Issue by SergeyOrl0v** [new92/IAM#3]
JSON Query to accounts/login/: Could not find "window._sharedData" in html response. [retrying; skip with ^C]
JSON Query to accounts/login/: Could not find "window._sharedData" in html response. [retrying; skip with ^C]
[!] Error !
[*] Error message ==> JSON Query to accounts/login/: Could not find "window._sharedData" in html response.

**Comment by new92** [comment]
Hey @SergeyOrl0v sorry for my late reply. So have you tried using the script with a different account ? If yes maybe try a cooldown (wait a couple of days before using it again). If the error persists reopen this issue.

**Comment by new92** [comment]
Hey @SergeyOrl0v to solve the bug, follow these steps:

1. Download [this script](https://raw.githubusercontent.com/instaloader/instaloader/master/docs/codesnippets/615_import_firefox_session.py)
2. Login to Instagram in Firefox
3. Execute the snippet, e.g. with python 615_import_firefox_session.py
The eror should've been resolved. If you haven't pre-installed Firefox download it from [here](https://www.mozilla.org/en-US/firefox/new/)
